"""gxana config export: the flat channel.kv file the C++ macros read (gxana::ChannelInfo)."""
import hashlib
import shutil
from pathlib import Path

import pytest

from gxana import cli, config
from gxana.paths import repo_root

PERIODS = ("2017-01", "2018-01", "2018-08")


def _kv(text):
    return dict(line.split("=", 1) for line in text.splitlines() if line and not line.startswith("#"))


def test_kpkpxim_periods_dirs_titles_and_mc_sample():
    text = config.channel_kv("kpkpxim")
    assert text.startswith("# generated by gxana config export --channel kpkpxim; do not edit\n")
    kv = _kv(text)
    assert kv["channel"] == "kpkpxim"
    assert kv["periods"] == ",".join(PERIODS)
    assert [kv[f"period.{p}.dir"] for p in PERIODS] == ["Spring_2017", "Spring_2018", "Fall_2018"]
    assert [kv[f"period.{p}.title"] for p in PERIODS] == ["Spring 2017", "Spring 2018", "Fall 2018"]
    assert [kv[f"period.{p}.label"] for p in PERIODS] == ["sp17", "sp18", "fa18"]
    assert kv["stem.2017-01.data"] == "kpkpxim__M23_2017-01_ana56"
    assert kv["stem.2018-01.gen_amp_V2_ac_YstarRest"] == "kpkpxim__B4_M23_2018-01_ana03_gen_amp_V2_ac_YstarRest"
    assert kv["mc_sample"] == "gen_amp_V2_ac_YstarRest"


def test_stems_are_exactly_the_pairs_tree_stem_accepts():
    cfg = config.load_channel("kpkpxim")
    kv = _kv(config.channel_kv("kpkpxim"))
    stems = {k: v for k, v in kv.items() if k.startswith("stem.")}
    for key, value in stems.items():
        _, period, sample = key.split(".", 2)
        assert value == config.tree_stem(cfg, period, sample), key
    # launched for 2018-08 only: no stem for the other periods
    assert "stem.2017-01.Ystar2400_1600_genr8" not in stems
    assert stems["stem.2018-08.Ystar2400_1600_genr8"] == "kpkpxim__B4_M23_2018-08_ana02_Ystar2400_1600_genr8"
    assert len(stems) == sum(1 for p in PERIODS for s in cfg["samples"] if _accepts(cfg, p, s))


def _accepts(cfg, period, sample):
    try:
        config.tree_stem(cfg, period, sample)
        return True
    except config.ConfigError:
        return False


def test_source_md5_lines_cover_every_config_file():
    kv = _kv(config.channel_kv("kpkpxim"))
    cfg_dir = repo_root() / "analyses" / "kpkpxim" / "config"
    assert Path(kv["source_dir"]) == cfg_dir.resolve()
    names = sorted(p.name for p in cfg_dir.glob("*.yaml"))
    listed = sorted(k[len("source."):-len(".md5")] for k in kv if k.startswith("source.") and k.endswith(".md5"))
    assert listed == names
    for name in names:
        assert kv[f"source.{name}.md5"] == hashlib.md5((cfg_dir / name).read_bytes()).hexdigest()


def test_second_channel_without_mc_sample():
    kv = _kv(config.channel_kv("kpkpkmlamb"))
    assert "mc_sample" not in kv
    assert kv["period.2018-01.dir"] == "Spring_2018"
    assert kv["stem.2018-08.data"] == "kpkpkmlamb__B4_M18_2018-08_ana19"


def test_period_without_dir_is_a_config_error(tmp_path):
    cfg_dir = tmp_path / "analyses" / "toy" / "config"
    shutil.copytree(repo_root() / "analyses" / "kpkpxim" / "config", cfg_dir)
    periods = cfg_dir / "periods.yaml"
    periods.write_text(periods.read_text().replace(", dir: Spring_2017", ""))
    with pytest.raises(config.ConfigError, match=r"periods\.2017-01\.dir"):
        config.channel_kv("toy", root=tmp_path)


def test_cli_export_writes_under_gxana_output(tmp_path, monkeypatch, capsys):
    monkeypatch.setenv("GXANA_OUTPUT", str(tmp_path))
    assert cli.main(["config", "export", "--channel", "kpkpxim"]) == 0
    out = tmp_path / "kpkpxim" / "config" / "channel.kv"
    assert out.read_text() == config.channel_kv("kpkpxim")
    assert f"wrote {out}" in capsys.readouterr().out


def test_cli_export_out_option(tmp_path, capsys):
    out = tmp_path / "sub" / "c.kv"
    assert cli.main(["config", "export", "--channel", "kpkpkmlamb", "--out", str(out)]) == 0
    assert out.read_text() == config.channel_kv("kpkpkmlamb")


def test_cli_export_without_gxana_output_is_a_clean_error(monkeypatch, capsys):
    monkeypatch.delenv("GXANA_OUTPUT", raising=False)
    assert cli.main(["config", "export", "--channel", "kpkpxim"]) == 2
    assert "GXANA_OUTPUT is not set" in capsys.readouterr().err
