// ChannelInfo (channel.kv), ExpandPattern, MakePeriods, FillHists / FillPeriodHists against a
// direct RDataFrame fill, GetPeriodHists, MergeHists, DrawOverlay.
#include "gxana/common/Overlay.h"
#include "gxana/common/PeriodHists.h"
#include "gxana/common/Periods.h"

#include <ROOT/RDataFrame.hxx>
#include <TCanvas.h>
#include <TFile.h>
#include <TH1D.h>
#include <TH2D.h>
#include <TKey.h>
#include <TLegend.h>
#include <TMD5.h>
#include <TROOT.h>
#include <TRandom3.h>
#include <TSystem.h>
#include <TTree.h>

#include <cmath>
#include <fstream>
#include <functional>
#include <iostream>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

static int failures = 0;
#define CHECK(cond)                                                                   \
    do {                                                                              \
        if (!(cond)) {                                                                \
            std::cerr << __FILE__ << ":" << __LINE__ << ": CHECK failed: " #cond "\n"; \
            ++failures;                                                               \
        }                                                                             \
    } while (0)

static bool Throws(const std::function<void()>& f, const std::string& part)
{
    try {
        f();
    } catch (const std::exception& e) {
        if (std::string(e.what()).find(part) != std::string::npos)
            return true;
        std::cerr << "wrong message: " << e.what() << " (want '" << part << "')\n";
        return false;
    }
    return false;
}

static void Write(const std::string& path, const std::string& text)
{
    std::ofstream(path) << text;
}

// Identical histograms: class, name, title, axes, every cell's content and error, entries.
static bool Same(const TH1* a, const TH1* b)
{
    if (!a || !b || std::string(a->ClassName()) != b->ClassName() || std::string(a->GetName()) != b->GetName() ||
        std::string(a->GetTitle()) != b->GetTitle() || a->GetNcells() != b->GetNcells() ||
        a->GetEntries() != b->GetEntries() || a->GetSumw2N() != b->GetSumw2N() ||
        a->GetXaxis()->GetXmin() != b->GetXaxis()->GetXmin() || a->GetXaxis()->GetXmax() != b->GetXaxis()->GetXmax())
        return false;
    for (int i = 0; i < a->GetNcells(); ++i)
        if (a->GetBinContent(i) != b->GetBinContent(i) || a->GetBinError(i) != b->GetBinError(i))
            return false;
    return true;
}

// A seeded tree: x, y, w (weight) and m (window variable).
static void MakeTree(const std::string& path, unsigned seed)
{
    TFile f(path.c_str(), "RECREATE");
    TTree t("t", "t");
    double x, y, w, m;
    t.Branch("x", &x);
    t.Branch("y", &y);
    t.Branch("w", &w);
    t.Branch("m", &m);
    TRandom3 r(seed);
    for (int i = 0; i < 2000; ++i) {
        x = r.Uniform(0, 5);
        y = r.Gaus(0, 1);
        w = r.Uniform(-0.2, 1.5);
        m = r.Uniform(1.28, 1.36);
        t.Fill();
    }
    t.Write();
}

static std::vector<std::string> Keys(TDirectory* d)
{
    std::vector<std::string> out;
    for (auto* obj : *d->GetListOfKeys())
        out.push_back(obj->GetName());
    return out;
}

int main()
{
    gROOT->SetBatch(true);
    const std::string tmp = std::string(gSystem->TempDirectory()) + "/gxana_test_periods_" + std::to_string(gSystem->GetPid());
    gSystem->mkdir(tmp.c_str(), true);
    const std::string cfg = tmp + "/config";
    gSystem->mkdir(cfg.c_str(), true);
    Write(cfg + "/periods.yaml", "periods: {}\n");
    std::unique_ptr<TMD5> md5(TMD5::FileChecksum((cfg + "/periods.yaml").c_str()));
    const std::string kv = tmp + "/channel.kv";
    const std::string body =
        "# generated by gxana config export --channel toy; do not edit\n"
        "channel=toy\nsource_dir=" + cfg + "\nsource.periods.yaml.md5=" + md5->AsString() + "\n"
        "periods=p1,p2\n"
        "period.p1.dir=Dir_One\nperiod.p1.title=One\nperiod.p1.label=o\n"
        "period.p2.dir=Dir_Two\nperiod.p2.title=Two\nperiod.p2.label=t\n"
        "stem.p1.data=toy__p1\nstem.p1.sim=toy__p1_sim\nstem.p2.data=toy__p2\nstem.p2.sim=toy__p2_sim\n"
        "mc_sample=sim\n";
    Write(kv, body);

    // ChannelInfo
    const auto info = gxana::ChannelInfo::LoadFile(kv);
    CHECK((info.PeriodNames() == std::vector<std::string>{"p1", "p2"}));
    CHECK(info.PeriodValue("p2", "dir") == "Dir_Two");
    CHECK(info.PeriodValue("p1", "title") == "One");
    CHECK(info.Stem("p1") == "toy__p1");
    CHECK(info.Stem("p2", "sim") == "toy__p2_sim");
    CHECK(info.Get("mc_sample") == "sim");
    CHECK(Throws([&] { info.Stem("p1", "other"); }, "no key stem.p1.other"));
    CHECK(Throws([&] { gxana::ChannelInfo::LoadFile(tmp + "/absent.kv"); }, "gxana config export"));
    {
        const char* prev = gSystem->Getenv("GXANA_OUTPUT");
        const std::string prevValue = prev ? prev : "";
        gSystem->Setenv("GXANA_OUTPUT", tmp.c_str());
        CHECK(Throws([&] { gxana::ChannelInfo::Load("nochannel"); }, "run gxana config export --channel nochannel"));
        if (prev)
            gSystem->Setenv("GXANA_OUTPUT", prevValue.c_str());
        else
            gSystem->Unsetenv("GXANA_OUTPUT");
    }
    Write(tmp + "/bad.kv", "channel=toy\nnot a pair\n");
    CHECK(Throws([&] { gxana::ChannelInfo::LoadFile(tmp + "/bad.kv"); }, "bad.kv:2: expected key=value"));
    Write(cfg + "/periods.yaml", "periods: {changed: 1}\n");
    CHECK(Throws([&] { gxana::ChannelInfo::LoadFile(kv); }, "run gxana config export --channel toy"));
    gSystem->Unlink((cfg + "/periods.yaml").c_str());
    CHECK(Throws([&] { gxana::ChannelInfo::LoadFile(kv); }, "is missing"));
    Write(cfg + "/periods.yaml", "periods: {}\n");  // same text as recorded: fresh again
    CHECK(gxana::ChannelInfo::LoadFile(kv).PeriodNames().size() == 2);

    // ExpandPattern, MakePeriods
    CHECK(gxana::ExpandPattern("a_{stem}_b{x}", {{"stem", "S"}, {"x", "1"}}) == "a_S_b1");
    CHECK(gxana::ExpandPattern("plain", {}) == "plain");
    CHECK(Throws([] { gxana::ExpandPattern("a_{nope}", {}); }, "unknown placeholder {nope}"));
    CHECK(Throws([] { gxana::ExpandPattern("a_{stem", {{"stem", "S"}}); }, "unclosed"));
    auto periods = gxana::MakePeriods(info, {"d/{stem}.root", "d/{mc_stem}_{period}.root", "d/thrown_{mc_stem}.root", ""});
    CHECK(periods.size() == 2);
    CHECK(periods[1].name == "p2" && periods[1].dir == "Dir_Two" && periods[1].Dir() == "Dir_Two");
    CHECK(periods[0].data == "d/toy__p1.root" && periods[0].mc == "d/toy__p1_sim_p1.root");
    CHECK(periods[1].thrown == "d/thrown_toy__p2_sim.root");
    auto noMc = gxana::MakePeriods(info, {"{stem}", "", "", "absent_sample"});  // {mc_stem} unused: not looked up
    CHECK(noMc[0].data == "toy__p1" && noMc[0].mc.empty());
    gxana::Period bare;
    bare.name = "2017-01";
    CHECK(bare.Dir() == "2017-01");

    // FillHists against the direct RDataFrame statements it replaces
    const std::string tree1 = tmp + "/tree1.root", tree2 = tmp + "/tree2.root";
    MakeTree(tree1, 1);
    MakeTree(tree2, 2);
    gxana::FillSpec spec;
    spec.tree = "t";
    spec.steps = {{"", "x > 0.5"}, {"xw", "x*w"}};
    spec.frames = {{"win", "m<1.334 && m>1.31"}};
    spec.hists = {
        {"h2_key", "", "; x; y", {"x", "y"}, {10, 0, 5, 8, -3, 3}, "w", ""},
        {"h1_win", "", " ; x; Events", {"x"}, {20, 0, 5}, "w", "win"},
        {"h1_plain", "named", "plain;x", {"y"}, {12, -3, 3}, "", ""},
        {"h1_xw", "", "", {"x"}, {20, 0, 5}, "xw", ""},
    };
    {
        TFile out((tmp + "/fill.root").c_str(), "RECREATE");
        gxana::FillHists(tree1, spec, &out, 0);
        CHECK(gDirectory == &out);
        CHECK((Keys(&out) == std::vector<std::string>{"h2_key", "h1_win", "h1_plain", "h1_xw"}));
        auto df = ROOT::RDataFrame("t", tree1).Filter("x > 0.5").Define("xw", "x*w");
        auto df1 = df.Filter("m<1.334 && m>1.31");
        auto r2 = df.Histo2D({"", "; x; y", 10, 0, 5, 8, -3, 3}, "x", "y", "w");
        auto r1 = df1.Histo1D({"", " ; x; Events", 20u, 0, 5}, "x", "w");
        auto rp = df.Histo1D({"named", "plain;x", 12u, -3, 3}, "y");
        auto rx = df.Histo1D({"", "", 20u, 0, 5}, "x", "xw");
        CHECK(Same(out.Get<TH2D>("h2_key"), r2.GetPtr()));
        CHECK(Same(out.Get<TH1D>("h1_win"), r1.GetPtr()));
        CHECK(Same(out.Get<TH1D>("h1_plain"), rp.GetPtr()));
        CHECK(Same(out.Get<TH1D>("h1_xw"), rx.GetPtr()));
        CHECK(std::string(out.Get<TH1D>("h1_plain")->GetName()) == "named");
        CHECK(std::string(out.Get<TH1D>("h1_win")->GetName()).empty());
        auto bad = spec;
        bad.hists = {{"k", "", "", {"x"}, {20, 0, 5}, "", "nowhere"}};
        CHECK(Throws([&] { gxana::FillHists(tree1, bad, &out, 0); }, "unknown frame nowhere"));
        bad.hists = {{"k", "", "", {"x", "y"}, {20, 0, 5}, "", ""}};
        CHECK(Throws([&] { gxana::FillHists(tree1, bad, &out, 0); }, "need 1 column"));
    }

    // FillPeriodHists: directories first, then per period per job; GetPeriodHists; MergeHists
    {
        std::vector<gxana::Period> ps = {{"p1", tree1, tree2, tree1, "Dir_One"}, {"p2", tree2, tree1, tree2, ""}};
        gxana::FillSpec one;
        one.tree = "t";
        one.hists = {{"y_data", "", "", {"y"}, {12, -3, 3}, "w", ""}};
        gxana::FillSpec two = one;
        two.hists = {{"y_mc", "", "", {"y"}, {12, -3, 3}, "", ""}};
        TFile out((tmp + "/periods.root").c_str(), "RECREATE");
        gxana::FillPeriodHists(ps, {{gxana::Input::Data, one}, {gxana::Input::MC, two}}, &out, 0);
        CHECK((Keys(&out) == std::vector<std::string>{"Dir_One", "p2"}));
        CHECK((Keys(out.GetDirectory("Dir_One")) == std::vector<std::string>{"y_data", "y_mc"}));
        auto data = gxana::GetPeriodHists<TH1D>(&out, ps, "y_data", "renamed");
        CHECK(data.size() == 2 && std::string(data[0]->GetName()) == "renamed");
        auto direct2 = ROOT::RDataFrame("t", tree2).Histo1D({"", "", 12u, -3, 3}, "y", "w");
        CHECK(data[1]->GetBinContent(4) == direct2->GetBinContent(4) && data[1]->GetEntries() == direct2->GetEntries());
        auto mc = gxana::GetPeriodHists<TH1D>(&out, ps, "y_mc");
        CHECK(std::string(mc[0]->GetName()).empty());
        CHECK(Throws([&] { gxana::GetPeriodHists<TH1D>(&out, ps, "absent"); }, "no TH1D Dir_One/absent"));
        CHECK(Throws([&] { gxana::GetPeriodHists<TH2D>(&out, ps, "y_data"); }, "no TH2D Dir_One/y_data"));
        std::unique_ptr<TH1D> manual((TH1D*)data[0]->Clone("sum"));
        manual->Add((TH1D*)data[1]->Clone());
        TH1D* merged = gxana::MergeHists(data, "sum");
        CHECK(Same(merged, manual.get()));
        CHECK(std::string(gxana::MergeHists(data)->GetName()) == "renamed");
        CHECK(Throws([] { gxana::MergeHists(std::vector<TH1D*>{}); }, "no histograms"));
        std::vector<gxana::Period> noFile = {{"p3", tree1, "", "", ""}};
        CHECK(Throws([&] { gxana::FillPeriodHists(noFile, {{gxana::Input::MC, two}}, &out, 0); }, "no input file"));
    }

    // DrawOverlay: the compare_plot statements
    {
        TH1D a("a", "a;x;y", 10, 0, 10), b("b", "b;x;y", 10, 0, 10);
        for (int i = 1; i <= 10; ++i) {
            a.SetBinContent(i, i);
            b.SetBinContent(i, i == 5 ? 100 : 1);  // peaked: higher than the first after area scaling
        }
        gxana::OverlayOpts o;
        o.saveName = tmp + "/overlay";
        o.legendTitle = "GlueX-I";
        o.axisTitle = "; m ;arb. units";
        o.label1 = "Thrown";
        o.label2 = "Input";
        TCanvas* c = gxana::DrawOverlay(&a, &b, o);
        CHECK(!gSystem->AccessPathName((tmp + "/overlay.pdf").c_str()));
        CHECK(std::string(c->GetName()) == "GlueX-I" && c->GetGridx() && c->GetGridy());
        // primitives: TFrame, first "hist", second "hist same", legend "same"
        auto* prims = c->GetListOfPrimitives();
        CHECK(prims->GetSize() == 4);
        auto* h0 = dynamic_cast<TH1*>(prims->At(1));
        auto* h1 = dynamic_cast<TH1*>(prims->At(2));
        auto* leg = dynamic_cast<TLegend*>(prims->At(3));
        CHECK(h0 && h1 && leg && h0 != &a && h1 != &b);
        CHECK(std::string(h0->GetName()) == "a" && std::string(prims->FirstLink()->Next()->GetOption()) == "hist");
        CHECK(std::abs(h1->Integral("width") - a.Integral("width")) < 1e-9);
        const double raised = h0->GetMaximum();
        CHECK(raised == h1->GetMaximum() * 1.2);
        CHECK(std::string(h0->GetTitle()).empty() && std::string(h0->GetXaxis()->GetTitle()) == " m ");
        CHECK(std::abs(leg->GetX1NDC() - 0.68) < 1e-12 && leg->GetNRows() == 3);
        CHECK(a.GetBinContent(1) == 1 && b.GetBinContent(5) == 100);  // inputs untouched
        // compare_iters_2D.C form: second drawn first, first as points "e1 same"; legend not drawn
        o.legendTitle = "points";
        o.drawLegend = false;
        o.firstAsPoints = true;
        o.legendTopRight = false;
        o.saveName = tmp + "/overlay_points";
        TCanvas* c2 = gxana::DrawOverlay(&a, &b, o);
        auto* p2 = c2->GetListOfPrimitives();
        CHECK(p2->GetSize() == 4);  // TFrame, second, first, title (no legend)
        CHECK(std::string(p2->At(1)->GetName()) == "b" && std::string(p2->At(2)->GetName()) == "a");
        CHECK(std::string(p2->FirstLink()->Next()->Next()->GetOption()) == "e1 same");
        CHECK(dynamic_cast<TH1*>(p2->At(2))->GetMarkerStyle() == 20);
        o.legendTitle = "noraise";
        o.raiseMaximum = false;
        o.firstAsPoints = false;
        o.saveName = tmp + "/overlay_noraise";
        TCanvas* c3 = gxana::DrawOverlay(&a, &b, o);
        CHECK(dynamic_cast<TH1*>(c3->GetListOfPrimitives()->At(1))->GetMaximum() != raised);
    }

    gSystem->Exec(("rm -rf " + tmp).c_str());
    if (failures)
        std::cerr << failures << " check(s) failed\n";
    else
        std::cout << "test_periods: all checks passed\n";
    return failures ? 1 : 0;
}
